receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"      
    const_labels:
      service: "AlloyEditorWebApi" 

processors:
  batch:                          
    timeout: 10s
    send_batch_size: 1000

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"     

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]