receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

exporters:
  prometheus:
    endpoint: otel-collector:8888
    resource_to_telemetry_conversion:
      enabled: true  # Включаем преобразование ресурсов в метки
    const_labels: {}  # Убираем все const_labels

processors:
  batch: {}
  # Убираем процессор resource, чтобы не перезаписывать атрибуты

extensions:
  health_check:
    endpoint: otel-collector:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]  # Убираем resource processor
      exporters: [prometheus]